### ISSUE TITLE
You have 1 week to have my servers IPs blocked

### ISSUE THREAD

**Issue by iRainDropp** [USBBios/Joker-Mirai-Botnet-Source-V1#1]
You guys have 1 week to block my servers IP address from your network or I will be contacting legal authorities and will be reporting your botnet. This is your one and only chance before I get the law involved and guess what? I don't give two fucks, I will spend my money until I am broke to take you guys down if you decide to ignore this.

**Comment by Crystallinqq** [comment]
😄

**Comment by Xiaro** [comment]
😄

**Comment by jakepriddle** [comment]
😄

**Comment by allbombson** [comment]
:smile:

**Comment by wizar-d** [comment]
😄

**Comment by iRainDropp** [comment]
K we get it lmao, I was pissed. Ya'll sad asf ngl

**Comment by jakepriddle** [comment]
lol

**Comment by allbombson** [comment]
:smile:

**Comment by Paralusion** [comment]
can you also take off my ip? 184.13.161.248 thank you

**Comment by 0x150** [comment]
omg police will be involved 😳😳😳😳😳

please dont report this to the fbi 😥😥😥😥😓😓
